# Generated by Django 4.0.2 on 2022-02-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='AllData',
        ),
    ]
