# Generated by Django 4.0.2 on 2022-02-18 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_rename_data_alldata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
